[package]
name = "jsonschemagen"
version = "0.1.0"
edition = "2024"

[dependencies]
comtrya-lib = { path = "../lib", version = "0.9.1" }
schemars = { workspace = true }
serde_json = { workspace = true }
